app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

##############################################################################
#Lucky controller
##############################################################################

numberLucky:
    path:     /lucky/number/{min}
    defaults:  { _controller: AppBundle:Lucky:number, min: 1 }
    methods:  [GET]
    requirements:
        min: '\d+'
hellooLucky:
    path:     /lucky/helloo/{name}
    defaults:  { _controller: AppBundle:Lucky:helloo}
    methods:  [POST,GET]

testLucky:
    path:     /lucky/test/{name}
    defaults:  { _controller: AppBundle:Lucky:test}
    methods:  [POST,GET]

##############################################################################
#Security controller
##############################################################################

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods:  [GET,POST]

checkSesionSecurity:
    path:     /Security/checkSesion/
    defaults: { _controller: AppBundle:Security:checkSesion }
    methods:  [GET]

logout:
    path: /logout

##############################################################################
#Signin controller
##############################################################################

collegeSignin:
    path:     /Signin/college/
    defaults:  { _controller: AppBundle:Signin:college }
    methods:  [POST]

studentSignin:
    path:     /Signin/student/
    defaults:  { _controller: AppBundle:Signin:student }
    methods:  [POST]

##############################################################################
# ProfileStudent controler
##############################################################################

getProfileStudent:
    path:     /ProfileStudent/get/
    defaults:  { _controller: AppBundle:ProfileStudent:get}
    methods:  [GET]

updatePasswordProfileStudent:
    path:     /ProfileStudent/updatePassword/
    defaults:  { _controller: AppBundle:ProfileStudent:updatePassword}
    methods:  [POST]

updateEmailProfileStudent:
    path:     /ProfileStudent/updateEmail/
    defaults:  { _controller: AppBundle:ProfileStudent:updateEmail}
    methods:  [POST]



##############################################################################
# ProfileCollege controler
##############################################################################

getProfileCollege:
    path:     /ProfileCollege/get/
    defaults:  { _controller: AppBundle:ProfileCollege:get}
    methods:  [GET]

getStudentsProfileCollege:
    path:     /ProfileCollege/getStudents/
    defaults:  { _controller: AppBundle:ProfileCollege:getStudents}
    methods:  [GET]

##############################################################################
# Incidence controler
##############################################################################

createIncidence:
    path:     /Incidence/create/
    defaults:  { _controller: AppBundle:Incidence:create}
    methods:  [POST]

getIncidence:
    path:     /Incidence/get/
    defaults:  { _controller: AppBundle:Incidence:get}
    methods:  [GET]

downloadIncidence:
    path:  /Incidence/download/{filename}
    defaults: { _controller: AppBundle:Incidence:download }
    methods:  [GET]

updateStateIncidence:
    path:     /Incidence/updateState/
    defaults:  { _controller: AppBundle:Incidence:updateState}
    methods:  [POST]

##############################################################################
# Message controler
##############################################################################

createMessage:
    path:     /Message/create/
    defaults:  { _controller: AppBundle:Message:create}
    methods:  [POST]

getMessage:
    path:     /Message/get/
    defaults:  { _controller: AppBundle:Message:get}
    methods:  [GET]

countUnreadMessage:
    path:     /Message/countUnread/
    defaults:  { _controller: AppBundle:Message:countUnread}
    methods:  [GET]

countUnreadStudentMessage:
    path:     /Message/countUnreadStudent/
    defaults:  { _controller: AppBundle:Message:countUnreadStudent}
    methods:  [GET]

openAllMessage:
    path:     /Message/openAll/
    defaults:  { _controller: AppBundle:Message:openAll}
    methods:  [POST]

openStudentMessage:
    path:     /Message/openStudent/{username_student}
    defaults:  { _controller: AppBundle:Message:openStudent}
    methods:  [POST]

openMessage:
    path:     /Message/open/
    defaults:  { _controller: AppBundle:Message:open}
    methods:  [POST]

downloadMessage:
    path:  /Message/download/{filename}
    defaults: { _controller: AppBundle:Message:download }
    methods:  [GET]

# Rent controler
createRent:
    path:     /Rent/create/
    defaults:  { _controller: AppBundle:Rent:create}
    methods:  [POST]

payRent:
    path:     /Rent/pay/
    defaults:  { _controller: AppBundle:Rent:pay}
    methods:  [POST]

getRent:
    path:     /Rent/get/
    defaults:  { _controller: AppBundle:Rent:get}
    methods:  [GET]

getUnpaidRent:
    path:     /Rent/getUnpaid/
    defaults:  { _controller: AppBundle:Rent:getUnpaid}
    methods:  [GET]

downloadRent:
    path:  /Rent/download/{filename}
    defaults: { _controller: AppBundle:Rent:download }
    methods:  [GET]

##############################################################################
# Room controler
##############################################################################

createRoom:
    path:     /Room/create/
    defaults:  { _controller: AppBundle:Room:create}
    methods:  [POST]

updateDate:
    path:     /Room/updateDate/
    defaults:  { _controller: AppBundle:Room:updateDate}
    methods:  [POST]

getAllRoom:
    path:     /Room/getAll/
    defaults:  { _controller: AppBundle:Room:getAll}
    methods:  [GET]

getOFFEREDRoom:
    path:     /Room/getOFFERED/
    defaults:  { _controller: AppBundle:Room:getOFFERED}
    methods:  [GET]

getFREERoom:
    path:     /Room/getFREE/
    defaults:  { _controller: AppBundle:Room:getFREE}
    methods:  [GET]

downloadRoom:
    path:  /Room/download/{filename}
    defaults: { _controller: AppBundle:Room:download }
    methods:  [GET]

getRoom:
    path:  /Room/get/{id}
    defaults: { _controller: AppBundle:Room:get }
    methods:  [GET]

getSearchAllRoom:
    path:  /Room/getSearchAll/
    defaults: { _controller: AppBundle:Room:getSearchAll }
    methods:  [GET]

getSearchRoom:
    path:  /Room/getSearch/
    defaults: { _controller: AppBundle:Room:getSearch }
    methods:  [GET]

getAllCompanyNameRoom:
    path:  /Room/getAllCompanyName/
    defaults: { _controller: AppBundle:Room:getAllCompanyName }
    methods:  [GET]

removeRoom:
    path:  /Room/remove/{id}
    defaults: { _controller: AppBundle:Room:remove }
    methods:  [POST]

##############################################################################
# Bid controler
##############################################################################

createBid:
    path:     /Bid/create/
    defaults:  { _controller: AppBundle:Bid:create}
    methods:  [POST]

getBidsRoomBid:
    path:  /Bid/getBidsRoom/{id}
    defaults: { _controller: AppBundle:Bid:getBidsRoom }
    methods:  [GET]

getBid:
    path:  /Bid/get/{id}
    defaults: { _controller: AppBundle:Bid:get }
    methods:  [GET]

removeBid:
    path:  /Bid/remove/{id}
    defaults: { _controller: AppBundle:Bid:remove }
    methods:  [POST]

removeBidsRoomBid:
    path:  /Bid/removeBidsRoom/{id}
    defaults: { _controller: AppBundle:Bid:removeBidsRoom }
    methods:  [POST]

removeBidsStudentBid:
    path:  /Bid/removeBidsStudent/{username}
    defaults: { _controller: AppBundle:Bid:removeBidsStudent }
    methods:  [POST]


removeBidRoomStudentBid:
    path:  /Bid/removeBidRoomStudent/
    defaults: { _controller: AppBundle:Bid:removeBidRoomStudent }
    methods:  [POST]

##############################################################################
# Agreement controler
##############################################################################

createAgreement:
    path:     /Agreement/create/{room_id}/{username}
    defaults:  { _controller: AppBundle:Agreement:create}
    methods:  [POST]

removeAgreement:
    path:     /Agreement/remove/
    defaults:  { _controller: AppBundle:Agreement:remove}
    methods:  [POST]

acceptAgreement:
    path:     /Agreement/accept/
    defaults:  { _controller: AppBundle:Agreement:accept}
    methods:  [POST]

assignedRoomsAgreement:
    path:     /Agreement/assignedRooms/
    defaults:  { _controller: AppBundle:Agreement:assignedRooms}
    methods:  [POST]

downloadAgreement:
    path:  /Agreement/download/{filename}
    defaults: { _controller: AppBundle:Agreement:download }
    methods:  [GET]

verifyUnsignedAgreement:
    path:  /Agreement/verifyUnsigned/
    defaults: { _controller: AppBundle:Agreement:verifyUnsigned }
    methods:  [GET]


roomVerifyUnsignedAgreement:
    path:  /Agreement/roomVerifyUnsigned/{room_id}
    defaults: { _controller: AppBundle:Agreement:roomVerifyUnsigned }
    methods:  [GET]
