app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

numberLucky:
    path:     /lucky/number/{min}
    defaults:  { _controller: AppBundle:Lucky:number, min: 1 }
    methods:  [GET]
    requirements:
        min: '\d+'
hellooLucky:
    path:     /lucky/helloo/{name}
    defaults:  { _controller: AppBundle:Lucky:helloo}
    methods:  [POST,GET]

testLucky:
    path:     /lucky/test/{name}
    defaults:  { _controller: AppBundle:Lucky:test}
    methods:  [POST,GET]

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods:  [GET,POST]

logout:
    path: /logout

collegeSignin:
    path:     /Signin/college/
    defaults:  { _controller: AppBundle:Signin:college }
    methods:  [POST]

studentSignin:
    path:     /Signin/student/
    defaults:  { _controller: AppBundle:Signin:student }
    methods:  [POST]


profileProfileStudent:
    path:     /ProfileStudent/profile/
    defaults:  { _controller: AppBundle:ProfileStudent:profile}
    methods:  [GET]

changePasswordProfileStudent:
    path:     /ProfileStudent/changePassword/
    defaults:  { _controller: AppBundle:ProfileStudent:changePassword}
    methods:  [POST]

changeEmailProfileStudent:
    path:     /ProfileStudent/changeEmail/
    defaults:  { _controller: AppBundle:ProfileStudent:changeEmail}
    methods:  [POST]


createIncidence:
    path:     /Incidence/create/
    defaults:  { _controller: AppBundle:Incidence:create}
    methods:  [POST]


getIncidence:
    path:     /Incidence/get/
    defaults:  { _controller: AppBundle:Incidence:get}
    methods:  [GET]


updateStateIncidence:
    path:     /Incidence/updateState/
    defaults:  { _controller: AppBundle:Incidence:updateState}
    methods:  [POST]
