# src/AppBundle/Resources/config/doctrine/Agreement.orm.yml
AppBundle\Entity\Agreement:
    type: entity
    table: agreement
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            unique: TRUE
    fields:
        price:
            type: float
            unique: FALSE
        date_start_school:
            type: datetime
            unique: FALSE
        date_end_school:
            type: datetime
            unique: FALSE
        date_signed:
            type: datetime
            unique: FALSE
            nullable: TRUE
        file_agreement:
            type: string
            length: 60
            unique: FALSE
            nullable: TRUE
        file_agreement_signed:
            type: string
            length: 60
            unique: FALSE
            nullable: TRUE

    manyToOne:
        student:
            targetEntity: Student
            inversedBy: agreements
            joinColumn:
                name: student_username
                referencedColumnName: username

        room:
            targetEntity: Room
            inversedBy: agreements
            joinColumn:
                name: room_id
                referencedColumnName: id
