# src/AppBundle/Resources/config/doctrine/College.orm.yml
AppBundle\Entity\College:
    type: entity
    table: colleges
    id:
        username:
            type: string
            length: 9
            unique: true
    fields:
        password:
            type: string
            length: 64
            unique: false
        email:
            type: string
            length: 60
            unique: false
        isActive:
            type: boolean
            column: is_active
        companyName:
            type: string
            length: 60
            unique: false
            column: company_name
        address:
            type: string
            length: 200
            unique: false
        latitude:
            type: float
            unique: false
        longitude:
            type: float
            unique: false
        telephone:
            type: string
            length: 12
            unique: false
        url:
            type: string
            length: 60
            unique: false
        wifi:
            type: boolean
            unique: false
        elevator:
            type: boolean
            unique: false
        canteen:
            type: boolean
            unique: false
        hours24:
            type: boolean
            unique: false
        laundry:
            type: boolean
            unique: false
        gym:
            type: boolean
            unique: false
        study_room:
            type: boolean
            unique: false
        heating:
            type: boolean
            unique: false
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: college
        rooms:
            targetEntity: Room
            mappedBy: college
        banks:
            targetEntity: Bank
            mappedBy: college
        responsible_persons:
            targetEntity: Responsible_person
            mappedBy: college
