# src/AppBundle/Resources/config/doctrine/Rent.orm.yml
AppBundle\Entity\Rent:
    type: entity
    table: rent
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            unique: TRUE
    fields:
        status_paid:
            type: boolean
            unique: FALSE
        price:
            type: float
            unique: FALSE
        date:
            type: datetime
            unique: FALSE
        file_receipt:
            type: string
            length: 60
            unique: FALSE
            nullable: TRUE
        date_paid:
            type: datetime
            unique: FALSE
            nullable: TRUE
        idTransaction:
            type: string
            length: 60
            unique: FALSE
            nullable: TRUE
    manyToOne:
        student:
            targetEntity: Student
            inversedBy: rents
            joinColumn:
                name: student_username
                referencedColumnName: username
