# src/AppBundle/Resources/config/doctrine/ResponsiblePerson.orm.yml
AppBundle\Entity\ResponsiblePerson:
    type: entity
    table: responsiblePerson
    id:
        DNI:
            type: string
            length: 10
            unique: True
    fields:
        email:
            type: string
            length: 30
            unique: FALSE
        name:
            type: string
            length: 30
            unique: FALSE
        job_position:
            type: string
            length: 30
            unique: FALSE
    manyToOne:
        college:
            targetEntity: College
            inversedBy: responsiblePersons
            joinColumn:
                name: college_username
                referencedColumnName: username
